# Generated by Django 3.2.5 on 2021-07-20 01:59

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('des_tipo_endereco', models.CharField(max_length=50, unique=True)),
                ('flg_ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('des_tipo_endereco',),
            },
        ),
    ]
