# Generated by Django 3.2.5 on 2021-07-20 16:57

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('product', '0002_auto_20210719_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('des_estabelecimento', models.CharField(max_length=150, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='des_estabelecimento', unique=True)),
                ('imagem', models.ImageField(blank=True, upload_to='marketplace/%Y')),
                ('flg_ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('des_estabelecimento',),
            },
        ),
        migrations.CreateModel(
            name='EstabelecimentoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('num_estoque', models.CharField(max_length=150)),
                ('vlr_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('flg_ativo', models.BooleanField(default=True)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.produto')),
            ],
            options={
                'ordering': ('id_produto',),
            },
        ),
        migrations.CreateModel(
            name='EstabelecimentoEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('des_cep', models.CharField(max_length=8)),
                ('des_logradouro', models.CharField(max_length=150)),
                ('des_numero', models.CharField(max_length=10)),
                ('des_bairro', models.CharField(max_length=150)),
                ('des_cidade', models.CharField(max_length=150)),
                ('des_estado', models.CharField(max_length=2)),
                ('des_complemento', models.CharField(max_length=150)),
                ('des_latitude', models.CharField(max_length=100)),
                ('des_longitude', models.CharField(max_length=100)),
                ('flg_ativo', models.BooleanField(default=True)),
                ('id_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace', to='marketplace.estabelecimento')),
                ('id_tipo_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='shop.tipoendereco')),
            ],
            options={
                'ordering': ('des_logradouro',),
            },
        ),
    ]
