# Generated by Django 3.2.5 on 2021-07-20 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_estabelecimentoproduto_id_estabelecimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estabelecimentoproduto',
            options={'ordering': ('produto_id',)},
        ),
        migrations.RenameField(
            model_name='estabelecimentoendereco',
            old_name='id_estabelecimento',
            new_name='estabelecimento',
        ),
        migrations.RenameField(
            model_name='estabelecimentoendereco',
            old_name='id_tipo_endereco',
            new_name='tipo_endereco',
        ),
        migrations.RenameField(
            model_name='estabelecimentoproduto',
            old_name='id_produto',
            new_name='produto',
        ),
        migrations.RemoveField(
            model_name='estabelecimentoproduto',
            name='id_estabelecimento',
        ),
        migrations.AddField(
            model_name='estabelecimentoproduto',
            name='estabelecimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentoproduto', to='marketplace.estabelecimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estabelecimentoproduto',
            name='num_estoque',
            field=models.IntegerField(),
        ),
    ]
