# Generated by Django 3.2.5 on 2021-07-18 23:15

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('des_categoria', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='des_categoria', unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('des_categoria',),
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('des_produto', models.CharField(max_length=150, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='des_produto', unique=True)),
                ('imagem', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('des_detalhes', models.TextField(blank=True)),
                ('des_medida', models.CharField(blank=True, max_length=50)),
                ('des_ingredientes', models.TextField(blank=True)),
                ('des_fabricante', models.CharField(max_length=150)),
                ('des_marca', models.CharField(blank=True, max_length=100)),
                ('flg_ativo', models.BooleanField(default=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.categoria')),
            ],
            options={
                'ordering': ('des_produto',),
            },
        ),
    ]
